# Generated by Django 4.1.2 on 2022-10-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='counteInStock',
            new_name='countInStock',
        ),
    ]
