# Generated by Django 4.1.2 on 2022-11-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_counteinstock_product_countinstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
